### PR TITLE
Delete `!agree` message, remove 5s sleep.

### PR DESCRIPTION
**Pull request by jchristgit**
remove the `!agree` message from members so we can enable read message history so people know what's going on - also remove the 5s sleep

### CODE REVIEW

**Review by Ma-wa-re — APPROVED** [review]

**Comment by emmiegit** [comment]
I know this is already closed, but I think for the future this should be `asyncio.gather()`'d

**Comment by jchristgit** [comment]
wow, good thinking keeping that e f f i c i e n c y in mind

**Comment by jackylam5** [comment]
oh the reason for that 5 sec sleep was because of discords limit of removing and adding roles. Sometimes it fails to give a role after you remove a role but the 5 sec fixed that problem.

**Comment by jchristgit** [comment]
Doesn't discord.py implement rate limiting itself though?

**Pull request merged**
